CREATE TABLE T_PP_USER_PROCESS
(
	cUser	 			NVARCHAR(20)	NOT NULL,
	cProcess			NVARCHAR(20)	NOT NULL,
	cIsActive			NVARCHAR(1) 	NOT NULL,
	PRIMARY KEY(cUser, cProcess),
	FOREIGN KEY(cUser) REFERENCES T_PP_USER(cUser),
	CONSTRAINT C_PP_USER_PROCESS_01 CHECK(cIsActive IN('Y','N'))
)
