CREATE TABLE T_PP_PROCESS
(
	cProcess 			NVARCHAR(20)	NOT NULL,
	cName				NVARCHAR(100)	NOT NULL,
	cShortName			NVARCHAR(20)	NOT NULL,
	nDisplayOrder		DECIMAL(2) 		NOT NULL,
	cIsActive			NVARCHAR(1) 	NOT NULL,
	cMajor				NVARCHAR(10)	NOT NULL,
	cMinor				NVARCHAR(10)	NOT NULL,
	PRIMARY KEY(cProcess),
	CONSTRAINT C_PP_PROCESS_01 CHECK(cIsActive IN('Y','N'))
)
