CREATE TABLE T_PP_FUNC
(
	cFunc	 			NVARCHAR(20)	NOT NULL,
	cName				NVARCHAR(100)	NOT NULL,
	cShortName			NVARCHAR(20)	NOT NULL,
	nDisplayOrder		DECIMAL(2) 		NOT NULL,
	cIsActive			NVARCHAR(1) 	NOT NULL,
	PRIMARY KEY(cFunc),
	CONSTRAINT C_PP_FUNC_01 CHECK(cIsActive IN('Y','N'))
)
