CREATE TABLE T_PP_LOGIN_ATTEMPT
(
	cUser	 			NVARCHAR(20)	NOT NULL,
	cDate				NVARCHAR(8)		NOT NULL,
	cTime    			NVARCHAR(6)		NOT NULL,
	cWasSuccessful		NVARCHAR(1)		NOT NULL,
	cIsAdmin   			NVARCHAR(1)		NOT NULL,
	cToken				NVARCHAR(50) 	NOT NULL,
	cStatus  			NVARCHAR(1) 	NOT NULL,
	cLogoutDate			NVARCHAR(8)		NULL,
	cLogoutTime			NVARCHAR(6)		NULL
	PRIMARY KEY(cUser, cDate, cTime),
	CONSTRAINT C_PP_LOGIN_ATTEMPT_01 CHECK(cWasSuccessful IN('Y','N')),
	CONSTRAINT C_PP_LOGIN_ATTEMPT_02 CHECK(cIsAdmin IN('Y','N')),
	CONSTRAINT C_PP_LOGIN_ATTEMPT_03 CHECK(cStatus IN('A','F','L','X'))
);
CREATE INDEX X_PP_LOGIN_ATTEMPT_01 ON T_PP_LOGIN_ATTEMPT(cUser, cDate DESC, cTime DESC);