CREATE TABLE T_PP_VERTICAL
(
	cVertical			NVARCHAR(20)	NOT NULL,
	cName				NVARCHAR(100)	NOT NULL,
	cShortName			NVARCHAR(20)	NOT NULL,
	nDisplayOrder		DECIMAL(2) 		NOT NULL,
	cIsActive			NVARCHAR(1) 	NOT NULL,
	PRIMARY KEY(cVertical),
	CONSTRAINT C_PP_VERTICAL_01 CHECK(cIsActive IN('Y','N'))
)