CREATE TABLE T_PP_USER_LOGIN_ATTEMPT
(
	cUser	 		NVARCHAR(20)	NOT NULL,
	cDate			NVARCHAR(8)		NOT NULL,
	cTime			NVARCHAR(6)		NOT NULL,
	cWasSuccessful	NVARCHAR(1)		NOT NULL,
	cToken			NVARCHAR(50)		NULL,
	cStatus			NVARCHAR(1)		NOT NULL,
	cLastActionDate NVARCHAR(8)		    NULL,
	cLastActionTime NVARCHAR(6)			NULL,
	CONSTRAINT C_PP_USER_LOGIN_ATTEMPT_01 CHECK(cWasSuccessful IN('Y','N')),
	CONSTRAINT C_PP_USER_LOGIN_ATTEMPT_02 CHECK(cStatus IN('A','C','F','X'))
)
CREATE INDEX X_PP_USER_LOGIN_ATTEMPT_01 ON T_PP_USER_LOGIN_ATTEMPT(cUser, cDate DESC, cTime DESC);