CREATE TABLE T_PP_USER
(
	cUser	 			NVARCHAR(20)	NOT NULL,
	cName				NVARCHAR(100)	NOT NULL,
	cRole     			NVARCHAR(1) 	NOT NULL,
	cIsActive			NVARCHAR(1) 	NOT NULL,
	PRIMARY KEY(cUser),
	CONSTRAINT C_PP_USER_01 CHECK(cRole IN('A','P')),
	CONSTRAINT C_PP_USER_02 CHECK(cIsActive IN('Y','N'))
)
